##### Numpy Exercises
1. How many negative numbers are there?
2. How many positive numbers are there?
3. How many even positive numbers are there?
4. If you were to add 3 to each data point, how many positive numbers would there be?
5. If you squared each number, what would the new mean and standard deviation be?
6. A common statistical operation on a dataset is centering. This means to adjust the data such that the mean of the data is 0. This is done by subtracting the mean from each data point. Center the data set. See this link for more on centering.
7. Calculate the z-score for each data point. Recall that the z-score is given by:

        z = (x-μ) / σ
        or 
        z = (observed value - mean of the sample) /
            standard deviation of the samlpe

8. Copy the setup and exercise directions from More Numpy Practice into your numpy_exercises.py and add your solutions.

In [111]:
import numpy as np
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])
print(len(a))

12


Question 1: How many negative numbers are there?

In [14]:
a < 0

array([False, False, False, False,  True,  True, False, False, False,
        True, False,  True])

In [13]:
# np.count_nonzero gives the number of True, i.e. number of elements that satisy the condition.
print(np.count_nonzero(a < 0))

4


In [114]:
# counts the numbers of Trues
(a < 0).sum()

4

Question 2: How many positive numbers are there?

In [15]:
a >= 0

array([ True,  True,  True,  True, False, False,  True,  True,  True,
       False,  True, False])

In [17]:
print(np.count_nonzero(a >= 0))

8


Question 3. How many even positive numbers are there?

In [25]:
even_numbers = a[a % 2 == 0]
even_numbers

array([ 4, 10, 12, -2,  0,  0,  0, -6])

In [28]:
print(np.count_nonzero(even_numbers > 0))

3


In [120]:
len(a[(a > 0) & (a % 2 == 0)])

3

Question 4: If you were to add 3 to each data point, how many positive numbers would be there 

In [33]:
add_a = a + 3
add_a

array([ 7, 13, 15, 26,  1,  2,  3,  3,  3, -3,  6, -4])

In [34]:
print(np.count_nonzero(add_a >= 0))

10


In [122]:
((a + 3) > 0).sum()

10

Question 5: If you squared each number, what would the new mean and standard deviation be?

In [41]:
square_a = a ** 2
square_a

array([ 16, 100, 144, 529,   4,   1,   0,   0,   0,  36,   9,  49])

In [42]:
square_a.std()

144.0243035046516

Question 6: A common statistical operation on a dataset is centering. This means to adjust the data such that the mean of the data is 0. This is done by subtracting the mean from each data point. Center the data set. 



In [43]:
# get the mean:
mean = np.mean(a)
mean

3.0

In [46]:
# center the data:
centered_data = a - mean
centered_data

array([  1.,   7.,   9.,  20.,  -5.,  -4.,  -3.,  -3.,  -3.,  -9.,   0.,
       -10.])

In [47]:
np.mean(centered_data)

0.0

Question 7: Calculate the z-score for each data point. Recall that the z-score is given by:
        
        z = (x-μ) / σ
        or 
        z = (observed value - mean of the sample) /
            standard deviation of the samlpe
              

In [50]:
z_score = (a - mean) / (a.std())
print(z_score)

[ 0.12403473  0.86824314  1.11631261  2.48069469 -0.62017367 -0.49613894
 -0.3721042  -0.3721042  -0.3721042  -1.11631261  0.         -1.24034735]


#### Question 8: 
Copy the setup and exercise directions from More Numpy Practice into your numpy_exercises.py and add your solutions.

### Setup 1

In [162]:
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [77]:
#Exercise 1 - Make a variable called sum_of_a to hold the sum of all the numbers in above list
sum_of_a = sum(a)
sum_of_a

55

In [78]:
#Exercise 2 - Make a variable named min_of_a to hold the minimum of all the numbers in the above list
min_of_a = min(a)
min_of_a

1

In [79]:
#Exercise 3 - Make a variable named max_of_a to hold the max number of all the numbers in the above list
max_of_a = max(a)
max_of_a

10

In [151]:
#Exercise 4 - Make a variable named mean_of_a to hold the average of all the numbers in the above list
mean_of_a = (sum(a)/len(a))
mean_of_a

3.0

In [58]:
#Exercise 5 - Make a variable named product_of_a to hold the product of multiplying all the numbers in the above list together
product_of_a = np.prod(a)
product_of_a

3628800

In [165]:
#Exercise 5
product_of_a = 1
for item in a:
    product_of_a *= item

product_of_a

3628800

In [81]:
#Exercise 6 - Make a variable named squares_of_a. It should hold each number in a squared like [1, 4, 9, 16, 25...]
squares_of_a = np.square(a)
squares_of_a

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [166]:
squares_of_a = []
for i in a:
    squares_of_a.append (i**2)
squares_of_a

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [84]:
#Exercise 7 - Make a variable named odds_in_a. It should hold only the odd numbers
odds_in_a = a[a % 2 == 1]
odds_in_a


array([1, 3, 5, 7, 9])

In [85]:
#Exercise 8 - Make a variable named evens_in_a. It should hold only the evens.
evens_in_a = a[a % 2 == 0]
evens_in_a

array([ 2,  4,  6,  8, 10])

In [167]:
evens_in_a = [num for num in a if num % 2 ==0]
evens_in_a

[2, 4, 6, 8, 10]

In [169]:
evens_in_a = []
for num in a:
    if num % 2 == 0:
        evens_in_a.append(num)

evens_in_a

[2, 4, 6, 8, 10]

What about life in two dimensions? A list of lists is matrix, a table, a spreadsheet, a chessboard...

### Setup 2: 
Consider what it would take to find the sum, min, max, average, sum, product, and list of 
squares for this list of two lists.

In [170]:
b = [
    [3, 4, 5],
    [6, 7, 8]
]

b = np.array(b)

In [96]:
#Exercise 1 - refactor the following to use numpy. Use sum_of_b as the variable.
#**Hint, you'll first need to make sure that the "b" variable is a numpy array**
sum_of_b = 0
for row in b:
    sum_of_b += sum(row)
sum_of_b

33

In [184]:
b.sum()

33

In [95]:
#Exercise 2 - refactor the following to use numpy. 
min_of_b = min(b[0]) if min(b[0]) <= min(b[1]) else min(b[1])  
min_of_b

3

In [183]:
b.min()

3

In [94]:
#Exercise 3 - refactor the following maximum calculation to find the answer with numpy.
max_of_b = max(b[0]) if max(b[0]) >= max(b[1]) else max(b[1])
max_of_b

8

In [182]:
b.max()

8

In [97]:
#Exercise 4 - refactor the following using numpy to find the mean of b
mean_of_b = (sum(b[0]) + sum(b[1])) / (len(b[0]) + len(b[1]))
mean_of_b

5.5

In [181]:
b.mean()

5.5

In [98]:
#Exercise 5 - refactor the following to use numpy for calculating the product of all numbers multiplied together.
product_of_b = 1
for row in b:
    for number in row:
        product_of_b *= number
product_of_b

20160

In [180]:
b.prod()

20160

In [179]:
np.prod(b)

20160

In [103]:
#Exercise 6 - refactor the following to use numpy to find the list of square
squares_of_b = []
for row in b:
    for number in row:
        squares_of_b.append(number**2)

In [104]:
squares_of_b

[9, 16, 25, 36, 49, 64]

In [186]:
b ** 2

array([[ 9],
       [16],
       [25],
       [36],
       [49],
       [64]])

In [105]:
# Exercise 7 - refactor using numpy to determine the odds_in_b
odds_in_b = []
for row in b:
    for number in row:
        if(number % 2 != 0):
            odds_in_b.append(number)
odds_in_b

[3, 5, 7]

In [188]:
b[b % 2 == 0]

array([4, 6, 8])

In [107]:
# Exercise 8 - refactor the following to use numpy to filter only the even numbers
evens_in_b = []
for row in b:
    for number in row:
        if(number % 2 == 0):
            evens_in_b.append(number)
evens_in_b

[4, 6, 8]

In [189]:
b[b % 2 == 0]

array([4, 6, 8])

In [108]:
# Exercise 9 - print out the shape of the array b.
np.shape(b)

(2, 3)

In [191]:
b.shape

(6, 1)

In [109]:
# Exercise 10 - transpose the array b.
np.transpose(b)

array([[3, 6],
       [4, 7],
       [5, 8]])

In [193]:
b.T

array([[3, 4, 5, 6, 7, 8]])

In [194]:
b.transpose()

array([[3, 4, 5, 6, 7, 8]])

In [204]:
# Exercise 11 - reshape the array b to be a single list of 6 numbers. (1 x 6)
# numpy.reshpae(a, newshape, order = 'C')
np.reshape(b,(6,))

array([3, 4, 5, 6, 7, 8])

In [198]:
#this creates an array with 0 columns
b.reshape(6)

array([3, 4, 5, 6, 7, 8])

In [208]:
#Exercise 12 - reshape the array b to be a list of 6 lists, each containing only 1 number (6 x 1)
(b).reshape(6,1)

array([[3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [207]:
#this creates an array with 1 column
np.reshape(b,(6,1))

array([[3],
       [4],
       [5],
       [6],
       [7],
       [8]])

### Setup 3

In [132]:
# HINT, you'll first need to make sure that the "c" variable is a numpy array prior to using numpy array methods.

In [226]:
c = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

c = np.array(c)

In [212]:
# Exercise 1 - Find the min, max, sum, and product of c.
c.min(), c.max(), c.sum(), c.prod()

(1, 9, 45, 362880)

In [213]:
# Exercise 2 - Determine the standard deviation of c.
c.std()

2.581988897471611

In [218]:
# Exercise 3 - Determine the variance of c.
c.std()

39.191835884530846

In [214]:
# Exercise 4 - Print out the shape of the array c
c.shape

(3, 3)

In [215]:
# Exercise 5 - Transpose c and print out transposed result.
c.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [227]:
# Exercise 6 - Get the dot product of the array c with c. 
np.dot(c,c)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [229]:
# Exercise 7 - Write the code necessary to sum up the result of c times c transposed. Answer should be 261
(c * c.T).sum()

261

In [230]:
# Exercise 8 - Write the code necessary to determine the product of c times c transposed. Answer should be 131681894400.
np.prod(c * c.T)

131681894400

### Setup 4

In [231]:
d = [
    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]
]
d = np.array(d)

In [144]:
# Exercise 1 - Find the sine of all the numbers in d

In [233]:
np.sin(d)

array([[ 0.89399666, -0.98803162,  0.85090352,  0.        ,  0.58061118,
        -0.80115264],
       [ 0.85090352, -0.89399666,  0.98803162, -0.17604595,  0.89399666,
         0.        ],
       [-0.30481062,  0.85090352, -0.85090352,  0.89399666, -0.85090352,
        -0.80115264]])

In [145]:
# Exercise 2 - Find the cosine of all the numbers in d

In [234]:
np.cos(d)

array([[-0.44807362,  0.15425145,  0.52532199,  1.        ,  0.81418097,
        -0.59846007],
       [ 0.52532199, -0.44807362,  0.15425145,  0.98438195, -0.44807362,
         1.        ],
       [-0.95241298,  0.52532199,  0.52532199, -0.44807362,  0.52532199,
        -0.59846007]])

In [146]:
# Exercise 3 - Find the tangent of all the numbers in d

In [235]:
np.tan(d)

array([[-1.99520041, -6.4053312 ,  1.61977519,  0.        ,  0.71312301,
         1.33869021],
       [ 1.61977519,  1.99520041,  6.4053312 , -0.17883906, -1.99520041,
         0.        ],
       [ 0.32004039,  1.61977519, -1.61977519, -1.99520041, -1.61977519,
         1.33869021]])

In [147]:
# Exercise 4 - Find all the negative numbers in d

In [238]:
d[d < 0]

array([-90, -30, -45, -45])

In [148]:
# Exercise 5 - Find all the positive numbers in d

In [239]:
d[d > 0]

array([ 90,  30,  45, 120, 180,  45, 270,  90,  60,  45,  90, 180])

In [ ]:
# Exercise 6 - Return an array of only the unique numbers in d.

In [240]:
np.unique(d)

array([-90, -45, -30,   0,  30,  45,  60,  90, 120, 180, 270])

In [241]:
# Exercise 7 - Determine how many unique numbers there are in d.
len(np.unique(d))

11

In [153]:
# Exercise 8 - Print out the shape of d.

In [242]:
d.shape

(3, 6)

In [243]:
# Exercise 9 - Transpose and then print out the shape of d.
d.T

array([[ 90,  45,  60],
       [ 30, -90,  45],
       [ 45, -30, -45],
       [  0, 270,  90],
       [120,  90, -45],
       [180,   0, 180]])

In [245]:
# Exercise 10 - Reshape d into an array of 9 x 2
d.reshape(9,2)

array([[ 90,  30],
       [ 45,   0],
       [120, 180],
       [ 45, -90],
       [-30, 270],
       [ 90,   0],
       [ 60,  45],
       [-45,  90],
       [-45, 180]])