##### Numpy Exercises
1. How many negative numbers are there?
2. How many positive numbers are there?
3. How many even positive numbers are there?
4. If you were to add 3 to each data point, how many positive numbers would there be?
5. If you squared each number, what would the new mean and standard deviation be?
6. A common statistical operation on a dataset is centering. This means to adjust the data such that the mean of the data is 0. This is done by subtracting the mean from each data point. Center the data set. See this link for more on centering.
7. Calculate the z-score for each data point. Recall that the z-score is given by:

        z = (x-μ) / σ
        or 
        z = (observed value - mean of the sample) /
            standard deviation of the samlpe

8. Copy the setup and exercise directions from More Numpy Practice into your numpy_exercises.py and add your solutions.

In [19]:
import numpy as np
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])
print(len(a))

12


Question 1: How many negative numbers are there?

In [14]:
a < 0

array([False, False, False, False,  True,  True, False, False, False,
        True, False,  True])

In [13]:
# np.count_nonzero gives the number of True, i.e. number of elements that satisy the condition.
print(np.count_nonzero(a < 0))

4


Question 2: How many positive numbers are there?

In [15]:
a >= 0

array([ True,  True,  True,  True, False, False,  True,  True,  True,
       False,  True, False])

In [17]:
print(np.count_nonzero(a >= 0))

8


Question 3. How many even positive numbers are there?

In [25]:
even_numbers = a[a % 2 == 0]
even_numbers

array([ 4, 10, 12, -2,  0,  0,  0, -6])

In [28]:
print(np.count_nonzero(even_numbers > 0))

3


Question 4: If you were to add 3 to each data point, how many positive numbers would be there 

In [33]:
add_a = a + 3
add_a

array([ 7, 13, 15, 26,  1,  2,  3,  3,  3, -3,  6, -4])

In [34]:
print(np.count_nonzero(add_a >= 0))

10


Question 5: If you squared each number, what would the new mean and standard deviation be?

In [41]:
square_a = a ** 2
square_a

array([ 16, 100, 144, 529,   4,   1,   0,   0,   0,  36,   9,  49])

In [42]:
square_a.std()

144.0243035046516

Question 6: A common statistical operation on a dataset is centering. This means to adjust the data such that the mean of the data is 0. This is done by subtracting the mean from each data point. Center the data set. 

